version: "3.4"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: scoreboard-app
    ports:
      - "3000:3000"
    environment:
      - WATCHPACK_POLLING=true
    networks:
      - web
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity

networks:
  web:
